<?php

/**
 * @file
 * Contains hook.
 */

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Database\Query\Condition;

/**
 * Implements hook_curl().
 */
function exc_curl($api_end_point, $http_header, $post_data) {
  $ch = curl_init($api_end_point);
  curl_setopt($ch, CURLOPT_HTTPHEADER, $http_header);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($post_data));
  $result = curl_exec($ch);
  curl_close($ch);
  return $result;
}

/**
 * Implements hook_page_attachments().
 */
function shorten_url_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'shorten_url/shorten_url_js';
}

/**
 * Implements hook_theme().
 */
function shorten_url_theme($existing, $type, $theme, $path) {
  return [
    'shorten_url_theme' => [
      'variables' => ['shorten_url_data' => NULL],
    ],
  ];
}

/**
 * Implements hook_views_query_alter().
 */
function shorten_url_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->storage->id() == 'shorten_url_data') {
    $uids = [\Drupal::currentUser()->id(), 0];
    $and = new Condition('AND');
    $and->condition("uid", $uids, 'IN');
    $query->addWhere('AND', $and);
  }
}
